import os
import json
import requests
from flask import Flask, request
import openai
import logging
from review_prompt import generate_review_prompt

app = Flask(__name__)
openai.api_key = os.environ.get("OPENAI_API_KEY")
gitlab_token = os.environ.get("GITLAB_TOKEN")
gitlab_base_url = os.environ.get("GITLAB_URL")
gitlab_api_base_url = (
    f"{gitlab_base_url.rstrip('/')}/api/v4" if gitlab_base_url else None
)


def _get_bool_env(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


log_level_name = os.environ.get("LOG_LEVEL", "INFO").upper()
log_level = getattr(logging, log_level_name, logging.INFO)
logging.basicConfig(level=log_level)
logger = logging.getLogger(__name__)

if log_level == logging.INFO and log_level_name != "INFO":
    logger.warning(
        "Invalid LOG_LEVEL '%s', defaulting to INFO",
        log_level_name,
    )

enable_merge_request_review = _get_bool_env("ENABLE_MERGE_REQUEST_REVIEW", True)
enable_push_review = _get_bool_env("ENABLE_PUSH_REVIEW", True)


@app.route("/webhook", methods=["POST"])
def webhook():
    expected_token = os.environ.get("EXPECTED_GITLAB_TOKEN")
    received_token = request.headers.get("X-Gitlab-Token")
    if received_token != expected_token:
        logger.warning("Unauthorized webhook request: invalid X-Gitlab-Token")
        return "Unauthorized", 403

    payload = request.json
    object_kind = payload.get("object_kind")
    logger.info("Received webhook: object_kind=%s", object_kind)

    if object_kind == "merge_request":
        if not enable_merge_request_review:
            return "merge_request handling disabled", 200
        action = payload["object_attributes"]["action"]
        if action != "open":
            return "Not a  PR open", 200

        project_id = payload["project"]["id"]
        mr_id = payload["object_attributes"]["iid"]
        logger.info(
            "Handling merge_request: project_id=%s, mr_id=%s, action=%s",
            project_id,
            mr_id,
            action,
        )
        changes_url = f"{gitlab_api_base_url}/projects/{project_id}/merge_requests/{mr_id}/changes"

        headers = {"Private-Token": gitlab_token}
        response = requests.get(changes_url, headers=headers)
        logger.info(
            "Fetched merge_request changes: url=%s, status_code=%s",
            changes_url,
            response.status_code,
        )
        mr_changes = response.json()

        messages = generate_review_prompt(mr_changes["changes"])

        try:
            completions = openai.ChatCompletion.create(
                model=os.environ.get("OPENAI_API_MODEL") or "gpt-3.5-turbo",
                temperature=0.2,
                stream=False,
                messages=messages,
            )
            answer = completions.choices[0].message["content"].strip()
            answer += (
                "\n\nThis comment was generated by an artificial intelligence duck."
            )
        except Exception as e:
            logger.exception("Failed to generate review for merge_request")
            answer = "I'm sorry, I'm not feeling well today. Please ask a human to review this PR."
            answer += (
                "\n\nThis comment was generated by an artificial intelligence duck."
            )
            answer += "\n\nError: " + str(e)

        comment_url = (
            f"{gitlab_api_base_url}/projects/{project_id}/merge_requests/{mr_id}/notes"
        )
        comment_payload = {"body": answer}
        comment_response = requests.post(
            comment_url, headers=headers, json=comment_payload
        )
        logger.info(
            "Posted merge_request review comment: project_id=%s, mr_id=%s, status_code=%s",
            project_id,
            mr_id,
            comment_response.status_code,
        )
    elif object_kind == "push":
        if not enable_push_review:
            return "push handling disabled", 200
        project_id = payload["project_id"]
        commit_id = payload["after"]
        logger.info(
            "Handling push event: project_id=%s, commit_id=%s",
            project_id,
            commit_id,
        )
        commit_url = f"{gitlab_api_base_url}/projects/{project_id}/repository/commits/{commit_id}/diff"

        headers = {"Private-Token": gitlab_token}
        response = requests.get(commit_url, headers=headers)
        logger.info(
            "Fetched commit diff: url=%s, status_code=%s",
            commit_url,
            response.status_code,
        )
        changes = response.json()

        messages = generate_review_prompt(changes)
        try:
            completions = openai.ChatCompletion.create(
                model=os.environ.get("OPENAI_API_MODEL") or "gpt-3.5-turbo",
                temperature=0.7,
                stream=False,
                messages=messages,
            )
            answer = completions.choices[0].message["content"].strip()
            answer += (
                "\n\nThis comment was generated by an artificial intelligence duck."
            )
        except Exception as e:
            logger.exception("Failed to generate review for commit")
            answer = "I'm sorry, I'm not feeling well today. Please ask a human to review this code change."
            answer += (
                "\n\nThis comment was generated by an artificial intelligence duck."
            )
            answer += "\n\nError: " + str(e)

        comment_url = f"{gitlab_api_base_url}/projects/{project_id}/repository/commits/{commit_id}/comments"
        comment_payload = {"note": answer}
        comment_response = requests.post(
            comment_url, headers=headers, json=comment_payload
        )
        logger.info(
            "Posted commit review comment: project_id=%s, commit_id=%s, status_code=%s",
            project_id,
            commit_id,
            comment_response.status_code,
        )
    else:
        logger.info("Ignoring unsupported object_kind: %s", object_kind)

    return "OK", 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9655)
