from typing import List

from .types import LLMReviewResult
from .time_utils import format_seconds


def build_ai_error_comment(prefix: str, error: Exception) -> str:
    lines: List[str] = [
        prefix,
        "",
        "```text",
        str(error),
        "```",
    ]
    return "\n".join(lines)


def build_llm_footer(result: LLMReviewResult) -> str:
    provider = result["provider"]
    model = result["model"]
    elapsed = result["elapsed_seconds"]

    parts: List[str] = [
        f"provider={provider}",
        f"model={model}",
        f"elapsed={format_seconds(elapsed)}",
    ]

    input_tokens = result.get("input_tokens")
    output_tokens = result.get("output_tokens")
    total_tokens = result.get("total_tokens")

    if input_tokens is not None:
        parts.append(f"input_tokens={input_tokens}")
    if output_tokens is not None:
        parts.append(f"output_tokens={output_tokens}")
    if total_tokens is not None:
        parts.append(f"total_tokens={total_tokens}")

    return "\n\nGenerated by LLM (" + ", ".join(parts) + ")"
