import logging
import os
from dataclasses import dataclass
from typing import Iterable, List

from .boy_scout_prompt import BoyScoutFile, generate_boy_scout_prompt
from .boy_scout_state import (
    mark_boy_scout_review_completed,
    release_boy_scout_review_claim,
)
from .gitlab_client import (
    get_merge_request_changes,
    get_repository_file_raw,
    post_merge_request_comment,
)
from .llm_client import generate_review_content_with_stats
from .types import GitDiffChange, LLMReviewResult, MergeRequestChangesResponse
from .utils.time_utils import format_seconds


logger = logging.getLogger(__name__)

_ALLOWED_CODE_EXTENSIONS = {
    ".py",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".java",
    ".kt",
    ".go",
    ".rb",
    ".rs",
    ".swift",
    ".c",
    ".h",
    ".cc",
    ".cpp",
    ".hpp",
    ".cs",
    ".php",
    ".scala",
    ".sql",
    ".sh",
    ".bash",
    ".zsh",
    ".yaml",
    ".yml",
    ".json",
    ".toml",
    ".ini",
    ".cfg",
    ".dockerfile",
}
_ALLOWED_CODE_FILENAMES = {
    "Dockerfile",
    "Makefile",
    "CMakeLists.txt",
}


@dataclass
class BoyScoutReviewTask:
    project_id: int
    merge_request_iid: int
    source_ref: str
    gitlab_api_base_url: str
    gitlab_access_token: str
    max_files: int
    max_file_chars: int
    max_total_chars: int


def _is_code_file(path: str) -> bool:
    filename = os.path.basename(path)
    if filename in _ALLOWED_CODE_FILENAMES:
        return True

    lower_path = path.lower()
    _, ext = os.path.splitext(lower_path)
    return ext in _ALLOWED_CODE_EXTENSIONS


def _collect_candidate_paths(changes: Iterable[GitDiffChange], max_files: int) -> List[str]:
    results: List[str] = []
    seen: set[str] = set()

    for change in changes:
        if change.get("deleted_file"):
            continue

        path = change.get("new_path") or change.get("old_path")
        if not path:
            continue
        if path in seen:
            continue
        if not _is_code_file(path):
            continue

        seen.add(path)
        results.append(path)
        if len(results) >= max_files:
            break

    return results


def _truncate_text(content: str, max_chars: int) -> tuple[str, bool]:
    if max_chars <= 0:
        return "", bool(content)
    if len(content) <= max_chars:
        return content, False
    return content[:max_chars], True


def _build_llm_footer(result: LLMReviewResult) -> str:
    provider = result["provider"]
    model = result["model"]
    elapsed = result["elapsed_seconds"]
    elapsed_display = format_seconds(elapsed)

    parts: List[str] = [
        f"provider={provider}",
        f"model={model}",
        f"elapsed={elapsed_display}",
    ]

    input_tokens = result.get("input_tokens")
    output_tokens = result.get("output_tokens")
    total_tokens = result.get("total_tokens")

    if input_tokens is not None:
        parts.append(f"input_tokens={input_tokens}")
    if output_tokens is not None:
        parts.append(f"output_tokens={output_tokens}")
    if total_tokens is not None:
        parts.append(f"total_tokens={total_tokens}")

    return "\n\nGenerated by LLM (" + ", ".join(parts) + ")"


def _build_comment_header() -> str:
    return (
        "### 🌲 Boy Scout Review (Open Event, One-time)\n"
        "이번 코멘트는 **diff 패치 리뷰와 별개**로, 변경된 코드 파일의 전체 본문을 기준으로\n"
        "점진적 리팩토링(보이스카웃 규칙) 제안을 제공합니다."
    )


def _build_no_target_files_comment() -> str:
    return (
        "### 🌲 Boy Scout Review (Open Event, One-time)\n"
        "이번 MR에서는 보이스카웃 리뷰 대상이 되는 코드 파일을 찾지 못해 분석을 생략했습니다."
    )


def run_boy_scout_review(task: BoyScoutReviewTask) -> None:
    """MR open 이벤트 1회성 보이스카웃 리뷰를 수행한다."""

    logger.info(
        "Running boy scout review: project_id=%s, mr_id=%s, source_ref=%s",
        task.project_id,
        task.merge_request_iid,
        task.source_ref,
    )

    try:
        mr_changes: MergeRequestChangesResponse = get_merge_request_changes(
            task.gitlab_api_base_url,
            task.gitlab_access_token,
            task.project_id,
            task.merge_request_iid,
        )
        if "changes" not in mr_changes:
            raise RuntimeError("Failed to fetch merge request changes for boy scout review")
        changes: List[GitDiffChange] = mr_changes.get("changes", [])

        candidate_paths = _collect_candidate_paths(changes, task.max_files)
        if not candidate_paths:
            post_merge_request_comment(
                task.gitlab_api_base_url,
                task.gitlab_access_token,
                task.project_id,
                task.merge_request_iid,
                _build_no_target_files_comment(),
            )
            mark_boy_scout_review_completed(task.project_id, task.merge_request_iid)
            return

        files: List[BoyScoutFile] = []
        consumed_chars = 0

        for path in candidate_paths:
            if consumed_chars >= task.max_total_chars:
                break

            try:
                raw_content = get_repository_file_raw(
                    api_base_url=task.gitlab_api_base_url,
                    access_token=task.gitlab_access_token,
                    project_id=task.project_id,
                    file_path=path,
                    ref=task.source_ref,
                )
            except Exception:
                logger.exception(
                    "Failed to fetch repository file for boy scout review: project_id=%s, mr_id=%s, path=%s",
                    task.project_id,
                    task.merge_request_iid,
                    path,
                )
                continue

            if not raw_content.strip():
                continue

            remaining = task.max_total_chars - consumed_chars
            allowed_for_this_file = min(task.max_file_chars, remaining)
            clipped, truncated = _truncate_text(raw_content, allowed_for_this_file)

            if not clipped.strip():
                continue

            files.append(
                {
                    "path": path,
                    "content": clipped,
                    "truncated": truncated,
                }
            )
            consumed_chars += len(clipped)

        if not files:
            post_merge_request_comment(
                task.gitlab_api_base_url,
                task.gitlab_access_token,
                task.project_id,
                task.merge_request_iid,
                _build_no_target_files_comment(),
            )
            mark_boy_scout_review_completed(task.project_id, task.merge_request_iid)
            return

        messages = generate_boy_scout_prompt(files)
        llm_result = generate_review_content_with_stats(messages)

        comment_body = (
            _build_comment_header()
            + "\n\n"
            + llm_result["content"]
            + _build_llm_footer(llm_result)
        )
        post_merge_request_comment(
            task.gitlab_api_base_url,
            task.gitlab_access_token,
            task.project_id,
            task.merge_request_iid,
            comment_body,
        )
        mark_boy_scout_review_completed(task.project_id, task.merge_request_iid)
    except Exception:
        logger.exception(
            "Failed to run boy scout review: project_id=%s, mr_id=%s",
            task.project_id,
            task.merge_request_iid,
        )
        release_boy_scout_review_claim(task.project_id, task.merge_request_iid)
