import os
import json
import logging

from flask import Flask, request

from .review_prompt import generate_review_prompt
from .gitlab_client import (
    get_merge_request_changes,
    post_merge_request_comment,
    get_commit_diff,
    post_commit_comment,
)
from .openai_service import generate_review_content


app = Flask(__name__)
gitlab_access_token = os.environ.get("GITLAB_ACCESS_TOKEN")
gitlab_base_url = os.environ.get("GITLAB_URL")
gitlab_api_base_url = (
    f"{gitlab_base_url.rstrip('/')}/api/v4" if gitlab_base_url else None
)


def _get_bool_env(name: str, default: bool) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


log_level_name = os.environ.get("LOG_LEVEL", "INFO").upper()
log_level = getattr(logging, log_level_name, logging.INFO)
logging.basicConfig(level=log_level)
logger = logging.getLogger(__name__)

if log_level == logging.INFO and log_level_name != "INFO":
    logger.warning(
        "Invalid LOG_LEVEL '%s', defaulting to INFO",
        log_level_name,
    )

enable_merge_request_review = _get_bool_env("ENABLE_MERGE_REQUEST_REVIEW", True)
enable_push_review = _get_bool_env("ENABLE_PUSH_REVIEW", True)

AI_PROGRESS_MESSAGE = (
    "AI가 코드를 검토 중입니다. 잠시만 기다려 주세요.\n"
    "\n"
    "이 코멘트는 자동으로 생성되었습니다."
)


def _build_ai_error_comment(prefix: str, error: Exception) -> str:
    lines = [
        prefix,
        "",
        "```text",
        str(error),
        "```",
    ]
    return "\n".join(lines)


def handle_merge_request_event(payload):
    if not enable_merge_request_review:
        return "merge_request handling disabled", 200

    action = payload["object_attributes"]["action"]
    if action != "open":
        return "Not a  PR open", 200

    project_id = payload["project"]["id"]
    mr_id = payload["object_attributes"]["iid"]
    logger.info(
        "Handling merge_request: project_id=%s, mr_id=%s, action=%s",
        project_id,
        mr_id,
        action,
    )

    # 진행중 안내 코멘트
    try:
        post_merge_request_comment(
            gitlab_api_base_url,
            gitlab_access_token,
            project_id,
            mr_id,
            AI_PROGRESS_MESSAGE,
        )
    except Exception:
        logger.exception(
            "Failed to post AI progress comment for merge_request: project_id=%s, mr_id=%s",
            project_id,
            mr_id,
        )

    mr_changes = get_merge_request_changes(
        gitlab_api_base_url,
        gitlab_access_token,
        project_id,
        mr_id,
    )

    messages = generate_review_prompt(mr_changes["changes"])

    try:
        answer = generate_review_content(
            messages=messages,
            model=os.environ.get("OPENAI_API_MODEL") or "gpt-5-mini",
            temperature=1.0,
        )
        answer += "\n\nThis comment was generated by an artificial intelligence duck."
        post_merge_request_comment(
            gitlab_api_base_url,
            gitlab_access_token,
            project_id,
            mr_id,
            answer,
        )
    except Exception as e:
        logger.exception("Failed to generate review for merge_request")
        error_comment = _build_ai_error_comment(
            "AI 코드 리뷰 생성에 실패했습니다. 사람이 직접 리뷰해야 합니다.",
            e,
        )
        try:
            post_merge_request_comment(
                gitlab_api_base_url,
                gitlab_access_token,
                project_id,
                mr_id,
                error_comment,
            )
        except Exception:
            logger.exception(
                "Failed to post AI error comment for merge_request: project_id=%s, mr_id=%s",
                project_id,
                mr_id,
            )

    return "OK", 200


def handle_push_event(payload):
    if not enable_push_review:
        return "push handling disabled", 200

    project_id = payload["project_id"]
    commit_id = payload["after"]
    logger.info(
        "Handling push event: project_id=%s, commit_id=%s",
        project_id,
        commit_id,
    )

    # 진행중 안내 코멘트
    try:
        post_commit_comment(
            gitlab_api_base_url,
            gitlab_access_token,
            project_id,
            commit_id,
            AI_PROGRESS_MESSAGE,
        )
    except Exception:
        logger.exception(
            "Failed to post AI progress comment for commit: project_id=%s, commit_id=%s",
            project_id,
            commit_id,
        )

    changes = get_commit_diff(
        gitlab_api_base_url,
        gitlab_access_token,
        project_id,
        commit_id,
    )

    messages = generate_review_prompt(changes)
    try:
        answer = generate_review_content(
            messages=messages,
            model=os.environ.get("OPENAI_API_MODEL") or "gpt-5-mini",
            temperature=1.0,
        )
        answer += "\n\nThis comment was generated by an artificial intelligence duck."
        post_commit_comment(
            gitlab_api_base_url,
            gitlab_access_token,
            project_id,
            commit_id,
            answer,
        )
    except Exception as e:
        logger.exception("Failed to generate review for commit")
        error_comment = _build_ai_error_comment(
            "AI 코드 리뷰 생성에 실패했습니다. 사람이 직접 리뷰해야 합니다.",
            e,
        )
        try:
            post_commit_comment(
                gitlab_api_base_url,
                gitlab_access_token,
                project_id,
                commit_id,
                error_comment,
            )
        except Exception:
            logger.exception(
                "Failed to post AI error comment for commit: project_id=%s, commit_id=%s",
                project_id,
                commit_id,
            )

    return "OK", 200


@app.route("/webhook", methods=["POST"])
def webhook():
    webhook_secret_token = os.environ.get("GITLAB_WEBHOOK_SECRET_TOKEN")
    received_token = request.headers.get("X-Gitlab-Token")
    if received_token != webhook_secret_token:
        logger.warning("Unauthorized webhook request: invalid X-Gitlab-Token")
        return "Unauthorized", 403

    payload = request.json
    object_kind = payload.get("object_kind")
    logger.info("Received webhook: object_kind=%s", object_kind)

    if object_kind == "merge_request":
        return handle_merge_request_event(payload)

    if object_kind == "push":
        return handle_push_event(payload)

    logger.info("Ignoring unsupported object_kind: %s", object_kind)

    return "OK", 200


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=9655)
