import logging
from dataclasses import dataclass
from typing import List

from .gitlab_client import (
    get_merge_request_changes,
    get_commit_diff,
    post_merge_request_comment,
    post_commit_comment,
)
from .openai_service import generate_review_content
from .review_prompt import generate_review_prompt


logger = logging.getLogger(__name__)


@dataclass
class MergeRequestReviewTask:
    project_id: int
    merge_request_iid: int
    gitlab_api_base_url: str
    gitlab_access_token: str
    openai_model: str


@dataclass
class PushReviewTask:
    project_id: int
    commit_id: str
    gitlab_api_base_url: str
    gitlab_access_token: str
    openai_model: str


def _build_ai_error_comment(prefix: str, error: Exception) -> str:
    lines: List[str] = [
        prefix,
        "",
        "```text",
        str(error),
        "```",
    ]
    return "\n".join(lines)


def run_merge_request_review(task: MergeRequestReviewTask) -> None:
    """머지 요청에 대한 AI 코드 리뷰를 수행하고 결과/에러 코멘트를 남긴다."""

    logger.info(
        "Running merge_request review: project_id=%s, mr_id=%s",
        task.project_id,
        task.merge_request_iid,
    )

    mr_changes = get_merge_request_changes(
        task.gitlab_api_base_url,
        task.gitlab_access_token,
        task.project_id,
        task.merge_request_iid,
    )

    messages = generate_review_prompt(mr_changes["changes"])

    try:
        answer = generate_review_content(
            messages=messages,
            model=task.openai_model,
            temperature=1.0,
        )
        answer += "\n\nThis comment was generated by an artificial intelligence duck."
        post_merge_request_comment(
            task.gitlab_api_base_url,
            task.gitlab_access_token,
            task.project_id,
            task.merge_request_iid,
            answer,
        )
    except Exception as e:  # noqa: BLE001 - 외부 API 호출 래핑을 위해 광범위 예외 처리
        logger.exception(
            "Failed to generate review for merge_request: project_id=%s, mr_id=%s",
            task.project_id,
            task.merge_request_iid,
        )
        error_comment = _build_ai_error_comment(
            "AI 코드 리뷰 생성에 실패했습니다. 사람이 직접 리뷰해야 합니다.",
            e,
        )
        try:
            post_merge_request_comment(
                task.gitlab_api_base_url,
                task.gitlab_access_token,
                task.project_id,
                task.merge_request_iid,
                error_comment,
            )
        except Exception:  # noqa: BLE001 - GitLab 코멘트 실패도 로깅만 수행
            logger.exception(
                "Failed to post AI error comment for merge_request: project_id=%s, mr_id=%s",
                task.project_id,
                task.merge_request_iid,
            )


def run_push_review(task: PushReviewTask) -> None:
    """푸시(커밋)에 대한 AI 코드 리뷰를 수행하고 결과/에러 코멘트를 남긴다."""

    logger.info(
        "Running push review: project_id=%s, commit_id=%s",
        task.project_id,
        task.commit_id,
    )

    changes = get_commit_diff(
        task.gitlab_api_base_url,
        task.gitlab_access_token,
        task.project_id,
        task.commit_id,
    )

    messages = generate_review_prompt(changes)

    try:
        answer = generate_review_content(
            messages=messages,
            model=task.openai_model,
            temperature=1.0,
        )
        answer += "\n\nThis comment was generated by an artificial intelligence duck."
        post_commit_comment(
            task.gitlab_api_base_url,
            task.gitlab_access_token,
            task.project_id,
            task.commit_id,
            answer,
        )
    except Exception as e:  # noqa: BLE001 - 외부 API 호출 래핑을 위해 광범위 예외 처리
        logger.exception(
            "Failed to generate review for commit: project_id=%s, commit_id=%s",
            task.project_id,
            task.commit_id,
        )
        error_comment = _build_ai_error_comment(
            "AI 코드 리뷰 생성에 실패했습니다. 사람이 직접 리뷰해야 합니다.",
            e,
        )
        try:
            post_commit_comment(
                task.gitlab_api_base_url,
                task.gitlab_access_token,
                task.project_id,
                task.commit_id,
                error_comment,
            )
        except Exception:  # noqa: BLE001 - GitLab 코멘트 실패도 로깅만 수행
            logger.exception(
                "Failed to post AI error comment for commit: project_id=%s, commit_id=%s",
                task.project_id,
                task.commit_id,
            )
